### ISSUE TITLE
Output is not really a path, but a file; and has to exist

### ISSUE THREAD

**Issue by amenk** [trufi-association/osm-search-data-export#2]
./cli.js --input pbf --inpath ../osm/2019-08-31T01-03-01-addis-ababa.pbf --output json-compact --outpath search.json

Works only if search.json exists, same seems to be true for json-compact and sqlite

https://github.com/trufi-association/osm-search-data-export/blob/master/src/output/json.js#L5

Is the negation (!) intended? Or did want to ensure that the containing path is correct?

**Comment by mdoelker** [comment]
Alright, it was too late it seems. I'll look over these issues. Intention was to check that the output *path* exists and to overwrite existing files.

**Comment by mdoelker** [comment]
Resolved by 1ed865e3293d513ae9aae0b12217f1f37521612e
